version: "3.9"
services:
  web:
    build: .
    environment:
      - PYTHONPATH=.
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: sh web_starter.sh

  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    build: .
    environment:
      - PYTHONPATH=.
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    command: sh worker_starter.sh

