version: "3.9"
services:
  web:
    build: .
    environment:
      - PYTHONPATH=.
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - broker
    command: sh web_starter.sh

  broker:
    image: redis

  worker:
    build: .
    environment:
      - PYTHONPATH=.
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - broker
    command: sh worker_starter.sh

